/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AzListRouteImport } from './routes/az-list'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as DonghuaAzRouteImport } from './routes/donghua-az'
import { Route as DonghuaCompletedRouteImport } from './routes/donghua-completed'
import { Route as DonghuaGenresRouteImport } from './routes/donghua-genres'
import { Route as DonghuaOngoingRouteImport } from './routes/donghua-ongoing'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as GlobalChatRouteImport } from './routes/global-chat'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as OngoingRouteImport } from './routes/ongoing'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime.$animeId'
import { Route as DonghuaGenreSlugRouteImport } from './routes/donghua-genre.$slug'
import { Route as DonghuaSlugRouteImport } from './routes/donghua.$slug'
import { Route as KomikIndexRouteImport } from './routes/komik.index'
import { Route as KomikSlugRouteImport } from './routes/komik.$slug'
import { Route as KomikBerwarnaRouteImport } from './routes/komik.berwarna'
import { Route as KomikGenresRouteImport } from './routes/komik.genres'
import { Route as WatchEpisodeIdRouteImport } from './routes/watch.$episodeId'
import { Route as AnimeProviderAnimeIdRouteImport } from './routes/anime.$provider.$animeId'
import { Route as ApiPublicImgProxyRouteImport } from './routes/api/public/img-proxy'
import { Route as KomikReadChapterSlugRouteImport } from './routes/komik.read.$chapterSlug'
import { Route as KomikTypeTypeRouteImport } from './routes/komik.type.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AzListRoute = AzListRouteImport.update({
  id: '/az-list',
  path: '/az-list',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const DonghuaAzRoute = DonghuaAzRouteImport.update({
  id: '/donghua-az',
  path: '/donghua-az',
  getParentRoute: () => rootRouteImport,
} as any)
const DonghuaCompletedRoute = DonghuaCompletedRouteImport.update({
  id: '/donghua-completed',
  path: '/donghua-completed',
  getParentRoute: () => rootRouteImport,
} as any)
const DonghuaGenresRoute = DonghuaGenresRouteImport.update({
  id: '/donghua-genres',
  path: '/donghua-genres',
  getParentRoute: () => rootRouteImport,
} as any)
const DonghuaOngoingRoute = DonghuaOngoingRouteImport.update({
  id: '/donghua-ongoing',
  path: '/donghua-ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalChatRoute = GlobalChatRouteImport.update({
  id: '/global-chat',
  path: '/global-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OngoingRoute = OngoingRouteImport.update({
  id: '/ongoing',
  path: '/ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DonghuaGenreSlugRoute = DonghuaGenreSlugRouteImport.update({
  id: '/donghua-genre/$slug',
  path: '/donghua-genre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DonghuaSlugRoute = DonghuaSlugRouteImport.update({
  id: '/donghua/$slug',
  path: '/donghua/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KomikIndexRoute = KomikIndexRouteImport.update({
  id: '/komik/',
  path: '/komik/',
  getParentRoute: () => rootRouteImport,
} as any)
const KomikSlugRoute = KomikSlugRouteImport.update({
  id: '/komik/$slug',
  path: '/komik/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KomikBerwarnaRoute = KomikBerwarnaRouteImport.update({
  id: '/komik/berwarna',
  path: '/komik/berwarna',
  getParentRoute: () => rootRouteImport,
} as any)
const KomikGenresRoute = KomikGenresRouteImport.update({
  id: '/komik/genres',
  path: '/komik/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchEpisodeIdRoute = WatchEpisodeIdRouteImport.update({
  id: '/watch/$episodeId',
  path: '/watch/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeProviderAnimeIdRoute = AnimeProviderAnimeIdRouteImport.update({
  id: '/anime/$provider/$animeId',
  path: '/anime/$provider/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgProxyRoute = ApiPublicImgProxyRouteImport.update({
  id: '/api/public/img-proxy',
  path: '/api/public/img-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const KomikReadChapterSlugRoute = KomikReadChapterSlugRouteImport.update({
  id: '/komik/read/$chapterSlug',
  path: '/komik/read/$chapterSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const KomikTypeTypeRoute = KomikTypeTypeRouteImport.update({
  id: '/komik/type/$type',
  path: '/komik/type/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/az-list': typeof AzListRoute
  '/completed': typeof CompletedRoute
  '/donghua-az': typeof DonghuaAzRoute
  '/donghua-completed': typeof DonghuaCompletedRoute
  '/donghua-genres': typeof DonghuaGenresRoute
  '/donghua-ongoing': typeof DonghuaOngoingRoute
  '/genres': typeof GenresRoute
  '/global-chat': typeof GlobalChatRoute
  '/history': typeof HistoryRoute
  '/ongoing': typeof OngoingRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/donghua-genre/$slug': typeof DonghuaGenreSlugRoute
  '/donghua/$slug': typeof DonghuaSlugRoute
  '/komik/$slug': typeof KomikSlugRoute
  '/komik/berwarna': typeof KomikBerwarnaRoute
  '/komik/genres': typeof KomikGenresRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/komik/': typeof KomikIndexRoute
  '/anime/$provider/$animeId': typeof AnimeProviderAnimeIdRoute
  '/api/public/img-proxy': typeof ApiPublicImgProxyRoute
  '/komik/read/$chapterSlug': typeof KomikReadChapterSlugRoute
  '/komik/type/$type': typeof KomikTypeTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/az-list': typeof AzListRoute
  '/completed': typeof CompletedRoute
  '/donghua-az': typeof DonghuaAzRoute
  '/donghua-completed': typeof DonghuaCompletedRoute
  '/donghua-genres': typeof DonghuaGenresRoute
  '/donghua-ongoing': typeof DonghuaOngoingRoute
  '/genres': typeof GenresRoute
  '/global-chat': typeof GlobalChatRoute
  '/history': typeof HistoryRoute
  '/ongoing': typeof OngoingRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/donghua-genre/$slug': typeof DonghuaGenreSlugRoute
  '/donghua/$slug': typeof DonghuaSlugRoute
  '/komik/$slug': typeof KomikSlugRoute
  '/komik/berwarna': typeof KomikBerwarnaRoute
  '/komik/genres': typeof KomikGenresRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/komik': typeof KomikIndexRoute
  '/anime/$provider/$animeId': typeof AnimeProviderAnimeIdRoute
  '/api/public/img-proxy': typeof ApiPublicImgProxyRoute
  '/komik/read/$chapterSlug': typeof KomikReadChapterSlugRoute
  '/komik/type/$type': typeof KomikTypeTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/az-list': typeof AzListRoute
  '/completed': typeof CompletedRoute
  '/donghua-az': typeof DonghuaAzRoute
  '/donghua-completed': typeof DonghuaCompletedRoute
  '/donghua-genres': typeof DonghuaGenresRoute
  '/donghua-ongoing': typeof DonghuaOngoingRoute
  '/genres': typeof GenresRoute
  '/global-chat': typeof GlobalChatRoute
  '/history': typeof HistoryRoute
  '/ongoing': typeof OngoingRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/donghua-genre/$slug': typeof DonghuaGenreSlugRoute
  '/donghua/$slug': typeof DonghuaSlugRoute
  '/komik/$slug': typeof KomikSlugRoute
  '/komik/berwarna': typeof KomikBerwarnaRoute
  '/komik/genres': typeof KomikGenresRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/komik/': typeof KomikIndexRoute
  '/anime/$provider/$animeId': typeof AnimeProviderAnimeIdRoute
  '/api/public/img-proxy': typeof ApiPublicImgProxyRoute
  '/komik/read/$chapterSlug': typeof KomikReadChapterSlugRoute
  '/komik/type/$type': typeof KomikTypeTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/az-list'
    | '/completed'
    | '/donghua-az'
    | '/donghua-completed'
    | '/donghua-genres'
    | '/donghua-ongoing'
    | '/genres'
    | '/global-chat'
    | '/history'
    | '/ongoing'
    | '/schedule'
    | '/search'
    | '/anime/$animeId'
    | '/donghua-genre/$slug'
    | '/donghua/$slug'
    | '/komik/$slug'
    | '/komik/berwarna'
    | '/komik/genres'
    | '/watch/$episodeId'
    | '/komik/'
    | '/anime/$provider/$animeId'
    | '/api/public/img-proxy'
    | '/komik/read/$chapterSlug'
    | '/komik/type/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/az-list'
    | '/completed'
    | '/donghua-az'
    | '/donghua-completed'
    | '/donghua-genres'
    | '/donghua-ongoing'
    | '/genres'
    | '/global-chat'
    | '/history'
    | '/ongoing'
    | '/schedule'
    | '/search'
    | '/anime/$animeId'
    | '/donghua-genre/$slug'
    | '/donghua/$slug'
    | '/komik/$slug'
    | '/komik/berwarna'
    | '/komik/genres'
    | '/watch/$episodeId'
    | '/komik'
    | '/anime/$provider/$animeId'
    | '/api/public/img-proxy'
    | '/komik/read/$chapterSlug'
    | '/komik/type/$type'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/az-list'
    | '/completed'
    | '/donghua-az'
    | '/donghua-completed'
    | '/donghua-genres'
    | '/donghua-ongoing'
    | '/genres'
    | '/global-chat'
    | '/history'
    | '/ongoing'
    | '/schedule'
    | '/search'
    | '/anime/$animeId'
    | '/donghua-genre/$slug'
    | '/donghua/$slug'
    | '/komik/$slug'
    | '/komik/berwarna'
    | '/komik/genres'
    | '/watch/$episodeId'
    | '/komik/'
    | '/anime/$provider/$animeId'
    | '/api/public/img-proxy'
    | '/komik/read/$chapterSlug'
    | '/komik/type/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AzListRoute: typeof AzListRoute
  CompletedRoute: typeof CompletedRoute
  DonghuaAzRoute: typeof DonghuaAzRoute
  DonghuaCompletedRoute: typeof DonghuaCompletedRoute
  DonghuaGenresRoute: typeof DonghuaGenresRoute
  DonghuaOngoingRoute: typeof DonghuaOngoingRoute
  GenresRoute: typeof GenresRoute
  GlobalChatRoute: typeof GlobalChatRoute
  HistoryRoute: typeof HistoryRoute
  OngoingRoute: typeof OngoingRoute
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRoute
  DonghuaGenreSlugRoute: typeof DonghuaGenreSlugRoute
  DonghuaSlugRoute: typeof DonghuaSlugRoute
  KomikSlugRoute: typeof KomikSlugRoute
  KomikBerwarnaRoute: typeof KomikBerwarnaRoute
  KomikGenresRoute: typeof KomikGenresRoute
  WatchEpisodeIdRoute: typeof WatchEpisodeIdRoute
  KomikIndexRoute: typeof KomikIndexRoute
  AnimeProviderAnimeIdRoute: typeof AnimeProviderAnimeIdRoute
  ApiPublicImgProxyRoute: typeof ApiPublicImgProxyRoute
  KomikReadChapterSlugRoute: typeof KomikReadChapterSlugRoute
  KomikTypeTypeRoute: typeof KomikTypeTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/az-list': {
      id: '/az-list'
      path: '/az-list'
      fullPath: '/az-list'
      preLoaderRoute: typeof AzListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donghua-az': {
      id: '/donghua-az'
      path: '/donghua-az'
      fullPath: '/donghua-az'
      preLoaderRoute: typeof DonghuaAzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donghua-completed': {
      id: '/donghua-completed'
      path: '/donghua-completed'
      fullPath: '/donghua-completed'
      preLoaderRoute: typeof DonghuaCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donghua-genres': {
      id: '/donghua-genres'
      path: '/donghua-genres'
      fullPath: '/donghua-genres'
      preLoaderRoute: typeof DonghuaGenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donghua-ongoing': {
      id: '/donghua-ongoing'
      path: '/donghua-ongoing'
      fullPath: '/donghua-ongoing'
      preLoaderRoute: typeof DonghuaOngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-chat': {
      id: '/global-chat'
      path: '/global-chat'
      fullPath: '/global-chat'
      preLoaderRoute: typeof GlobalChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ongoing': {
      id: '/ongoing'
      path: '/ongoing'
      fullPath: '/ongoing'
      preLoaderRoute: typeof OngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donghua-genre/$slug': {
      id: '/donghua-genre/$slug'
      path: '/donghua-genre/$slug'
      fullPath: '/donghua-genre/$slug'
      preLoaderRoute: typeof DonghuaGenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donghua/$slug': {
      id: '/donghua/$slug'
      path: '/donghua/$slug'
      fullPath: '/donghua/$slug'
      preLoaderRoute: typeof DonghuaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komik/': {
      id: '/komik/'
      path: '/komik'
      fullPath: '/komik/'
      preLoaderRoute: typeof KomikIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komik/$slug': {
      id: '/komik/$slug'
      path: '/komik/$slug'
      fullPath: '/komik/$slug'
      preLoaderRoute: typeof KomikSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komik/berwarna': {
      id: '/komik/berwarna'
      path: '/komik/berwarna'
      fullPath: '/komik/berwarna'
      preLoaderRoute: typeof KomikBerwarnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komik/genres': {
      id: '/komik/genres'
      path: '/komik/genres'
      fullPath: '/komik/genres'
      preLoaderRoute: typeof KomikGenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$episodeId': {
      id: '/watch/$episodeId'
      path: '/watch/$episodeId'
      fullPath: '/watch/$episodeId'
      preLoaderRoute: typeof WatchEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$provider/$animeId': {
      id: '/anime/$provider/$animeId'
      path: '/anime/$provider/$animeId'
      fullPath: '/anime/$provider/$animeId'
      preLoaderRoute: typeof AnimeProviderAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img-proxy': {
      id: '/api/public/img-proxy'
      path: '/api/public/img-proxy'
      fullPath: '/api/public/img-proxy'
      preLoaderRoute: typeof ApiPublicImgProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komik/read/$chapterSlug': {
      id: '/komik/read/$chapterSlug'
      path: '/komik/read/$chapterSlug'
      fullPath: '/komik/read/$chapterSlug'
      preLoaderRoute: typeof KomikReadChapterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komik/type/$type': {
      id: '/komik/type/$type'
      path: '/komik/type/$type'
      fullPath: '/komik/type/$type'
      preLoaderRoute: typeof KomikTypeTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AzListRoute: AzListRoute,
  CompletedRoute: CompletedRoute,
  DonghuaAzRoute: DonghuaAzRoute,
  DonghuaCompletedRoute: DonghuaCompletedRoute,
  DonghuaGenresRoute: DonghuaGenresRoute,
  DonghuaOngoingRoute: DonghuaOngoingRoute,
  GenresRoute: GenresRoute,
  GlobalChatRoute: GlobalChatRoute,
  HistoryRoute: HistoryRoute,
  OngoingRoute: OngoingRoute,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRoute,
  DonghuaGenreSlugRoute: DonghuaGenreSlugRoute,
  DonghuaSlugRoute: DonghuaSlugRoute,
  KomikSlugRoute: KomikSlugRoute,
  KomikBerwarnaRoute: KomikBerwarnaRoute,
  KomikGenresRoute: KomikGenresRoute,
  WatchEpisodeIdRoute: WatchEpisodeIdRoute,
  KomikIndexRoute: KomikIndexRoute,
  AnimeProviderAnimeIdRoute: AnimeProviderAnimeIdRoute,
  ApiPublicImgProxyRoute: ApiPublicImgProxyRoute,
  KomikReadChapterSlugRoute: KomikReadChapterSlugRoute,
  KomikTypeTypeRoute: KomikTypeTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
